questions = [['How do you start Git repository?', 1],
             ['How do you determine the current state of the project?', 1],
             ['Command to put changed files to staging condition?', 1],
             ['How to show list of all the commits that have been made?', 1],
             ['How to create a new branch?', 2],
             ['How to show list of all branches?', 2],
             ['How to switch to master branch?', 2],
             ['Command to merge one branch to another?', 2],
             ["What is the datatype of 'one'?", 3],
             ["What does 'self' mean?", 3],
             ['What is the keyword for creating a new method?', 3],
             ['What type is :name?', 3],
             ['What is an object?', 4],
             ['What is a command for creating an object?', 4],
             ['What is the type of variable @@name?', 4],
             ['What is the keyword to define a ruby module?', 4],
             ['What SQL is generated to create a table in the database?', 5],
             ['What SQL is used to delete database?', 5],
             ['What attribute does find method use?', 5],
             ['What is the function that calls itself?', 6],
             ['Convert 1110 base-2 to the corresponding base-ten number', 6],
             ['Convert 63933 base-ten to the corresponding hexadecimal number', 6],
             ['What is n in O(n)?', 7],
             ['What is the average Big O performance of quicksort algorithm?', 7],
             ['What is the best Big O performance of bubble sort?', 7],
             ['What is the worst Big O performance of insertion sort?', 7]
]

questions.each { |question,test| Question.create!(body: question, test_id: test) }